export const signup = 'user/signup';
export const login = 'user/login';
export const otpVerify = 'user/verify';
export const editProfile = 'user/update';
export const changePassword = 'change-password';
export const forgetPassword = 'forgot-password';
export const logout = 'logout';
export const topRated = 'top-rated';
export const service = 'services';
export const providerDetails = (id) => `massager/services/${id}`;
